require("script/config/common_config.js");

var coinConfig={
Coin00:{
    coin_val:1,
    col_size:{width:50,height:50},
    actor:
    {
        imgfile:"item/coin_small.png",
        x_seg:7,
        y_seg:1,
        start:0,
        end:6,
        interval:0.1,
    },
},
Coin01:{
    coin_val:10,
    col_size:{width:90,height:90},
    actor:
    {
        imgfile:"item/coin_big.png",
        x_seg:7,
        y_seg:1,
        start:0,
        end:6,
        interval:0.1,
    },
}
};