require("script/config/common_config.js");

var deadEffect={
prefix:"monster/boomdead/",
start:1,
end:12,
interval:0.06,
};
var enemyConfig={
Enemy00:{
    hp:100,
    speed:200,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy01:{
    hp:100,
    speed:150,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy02:{
    hp:200,
    speed:300,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy03:{
    hp:250,
    speed:300,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy04:{
    hp:100,
    speed:300,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy05:{
    hp:100,
    speed:350,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy06:{
    hp:100,
    speed:400,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy07:{
    hp:100,
    speed:450,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy08:{
    hp:100,
    speed:500,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
Enemy09:{
    hp:100,
    speed:550,
    img_normal:"monster/level0/normal.png",
    img_hurt:"monster/level0/hurt.png",
    Fly:{
    prefix:"monster/level0/",
    start:1,
    end:3,
    interval:0.12,
    },
},
};