require("script/config/common_config.js");

var fighterConfig={
Fighter00:{
    name:"Assassin",
    col_size:{width:60,height:122},
    actor:
    {
        prefix:"fighter/assassin/",
        start:1,
        end:4,
        interval:0.12,
    },
},
Fighter01:{
    name:"princess",
    col_size:{width:60,height:122},
    magnet_size_n:{width:100,height:130},
    magnet_size_s:{width:300,height:300},
    img_hurt:"fighter/princess/cry.png",
    actor:
    {
        prefix:"fighter/princess/",
        start:1,
        end:4,
        interval:0.12,
    },
},
};